### ISSUE TITLE
Midi causes Segmentation fault by wrong assignment 

### ISSUE THREAD

**Issue by magdesign** [magdesign/IQSynth#1]
If in a custom midi configuration a CC# is assigned more than one time, the program crashes as soon as a midi input is done.

Ideas:
1.) If a CC# is already assigned, an error message will appear telling that this number is already assigned.

2.) Make it possible to assign a CC# to several functions, so its possible to control multiple functions with one controller.

**Comment by johnday-github** [comment]
Its supposed to handle 2 but its not been heavily tested recently, I'll look at this soon

**Comment by johnday-github** [comment]
I've managed to set a midi knob to M1 and M2 on an fx successfully, although I am seeing a problem with the range handling in my case.

**Comment by johnday-github** [comment]
definitely something wiffy going on in the midi sub-sytem, its actually some of the most dense code in the app and hardly tested yet, I'm working through it again now

**Comment by johnday-github** [comment]
released new version with a few tweaks, but nothing that seems related to the crash reported here. any more details about how to reproduce?

**Comment by johnday-github** [comment]
removed some deprecated code that might have caused these crashes. Released in 0.16.13

**Comment by johnday-github** [comment]
How to reproduce original problem?

**Comment by magdesign** [comment]
I could not reproduce the error with 0.16.16

So i am closing the issue until I find a new way to reproduce.
