### ISSUE TITLE
Directly import .png (with alpha)/.jpg sequences

### ISSUE THREAD

**Issue by magdesign** [magdesign/IQSynth#10]
would be nice to directly import sequence files name_####.png / name_####.jpg

**Comment by johnday-github** [comment]
I think I'll look at this next, I like the idea of importing a seq of png's!

**Comment by magdesign** [comment]
cool. ... get files directly from Blender to IQSynth.. looking forward to!

**Comment by johnday-github** [comment]
Hi @magdesign, I've released v0.18.3 which has images sequence import ability.

It was a little more work then I expected, it touched on quite a few areas, and as expected the playback of them is twice as much processing then the other videos. So use them sparingly.

PNG frames must be 8bit RGBA. Select import as usual, and once in the folder with the images click 'Select Folder' -> if the folder has only numbered files all of the same image type (jpg,png), then IQSynth will offer to import them as a sequence, you can then define the name and fps, and then confirm the import as usual. Hope is useful.

**Comment by johnday-github** [comment]
think I'll stop adding more things for a while and bug hunt.

**Comment by magdesign** [comment]
ok.
Think its a good idea to first get a really stable release!

**Comment by magdesign** [comment]
Thanks for adding this feature, you are still so pretty quick :-)
