### ISSUE TITLE
File access on USB media

### ISSUE THREAD

**Issue by magdesign** [magdesign/IQSynth#11]
When trying to import media from an USB drive, its only possible to access and load files which are located in the root directory of the drive.

It is not possible to access folders and sub-folders.

**Comment by johnday-github** [comment]
it should be able to access anywhere your user can access, If you can read/play those files under your normal login then I think this is another one for an emailed debug log.

**Comment by johnday-github** [comment]
BTW, it wont auto mount the usb drive for you, you might need to open the drive on the desktop first?

**Comment by johnday-github** [comment]
actually, I've just tested here and I didn't have to open the drive on the desktop first. So, suspect its a user permission problem, maybe a emailed debug log is required

**Comment by magdesign** [comment]
You where right, after clicking "Apply Permissions to Enclosed Files" it works to browse the drive within IQSynth.

![permission](https://user-images.githubusercontent.com/5273166/80316362-af8dc180-87fd-11ea-9b85-77275e857111.png)
