### ISSUE TITLE
Random media stepper

### ISSUE THREAD

**Issue by magdesign** [magdesign/IQSynth#13]
Can I somehow tell IQSynth to randomly step/play through a video like this:
(the base video is an endless tunnel animation, but with random step it scratches randomly through the video).
![random_stepper](https://user-images.githubusercontent.com/5273166/80400825-a19e7600-88bb-11ea-9ee7-069f045e3633.gif)

**Comment by johnday-github** [comment]
you could try the FrameJumper plugin

**Comment by johnday-github** [comment]
I don't think I've set up a direct midi option for this, you can send midi/audio to the frame jumper via the jump now trigger connected to a macro control, until I get some BPM options into the Macro controls

**Comment by magdesign** [comment]
I tried it!
 I nearly makes what is wanted, but it should jump randomly without mouse clicking... ;)

**Comment by johnday-github** [comment]
ah maybe a little update to that plugin would be useful

**Comment by magdesign** [comment]
I guess,
you have so much cool tools build in,  which all just need this extra bit of tweaking until they are perfect...

**Comment by johnday-github** [comment]
I'm attempting to update the frame jumper plugin with a few extra options for you (until I improve the macro options). Its an interesting problem, I thought I knew how I was going to handle plugin version upgrades but turns out I haven't actually done this before...

**Comment by magdesign** [comment]
LOOKING FORWARD TO :-)

**Comment by johnday-github** [comment]
I wasn't far off on the design. I'd bypassed the plugin versions in the code as it was still quite new. I think I just need to add a couple of bits to make it more robust. Then plugin versions should be better handled. Hope to get this around to this soon (maybe weekend).

**Comment by johnday-github** [comment]
took a little longer then expected, but new FrameJumper 0.4 plugin now in collection, it has on beat options, first update to IQSynth 0.18.0, this allows plugins to properly update/upgrade as you'd expect.

**Comment by magdesign** [comment]
Thanks!
This is amazing, is exactly what I was missing.... 
..now I am ready for a gig with IQSynth.
(for the mapping stuff I use a second computer with a grabber and Mapio, maybe for future we could use NDI. For this we would also need the option to bring another software to front. But for now I am happy :-)
