### ISSUE TITLE
Reduction of clicks

### ISSUE THREAD

**Issue by magdesign** [magdesign/IQSynth#14]
On set, a VJ knows what he wants to do on screen, therefore it would be very nice if you could reduce the click amount:

- dropping a video to an empty  slot, the dropped video starts playing by default
- dropping an effect to to the FX slot would automatically activate/enable it

just an idea to be quicker on set....

**Comment by johnday-github** [comment]
I want to allow multiple ways to 'play', these seemed to work, so checkout the new version 0.16.15

**Comment by johnday-github** [comment]
Its the 2 new options/buttons  'AP' : autoplay for slots, dropped in slot will be auto triggered,  'XAP'  : FX autoplay, although fx were always enabled when dropped into place, this causes them to be fully faded in.

**Comment by magdesign** [comment]
This is great, thank you so much!

For the documentation, here the green "AP" autoplay knob:

![autoplay](https://user-images.githubusercontent.com/5273166/80540109-fa980800-89a8-11ea-989d-d447fabae1c6.gif)

and here the pink "xaf" autofx knob:

![autoFX](https://user-images.githubusercontent.com/5273166/80540123-01bf1600-89a9-11ea-8560-77fe60efadd9.gif)

**Comment by magdesign** [comment]
Now I am much faster in my creative and chaotic way of making live visuals..

**Comment by johnday-github** [comment]
v0.16.17 - some of the global settings are now stored with the user startup config, inc the 2 new recent ones added for this ticket
