### ISSUE TITLE
Playback freezes when moving playing media in slot

### ISSUE THREAD

**Issue by magdesign** [magdesign/IQSynth#16]
When moving media which is playing, it somehow freezes on the output:

![move_error](https://user-images.githubusercontent.com/5273166/82266651-8975c000-996a-11ea-8be0-3777b1b96ac2.gif)

Stopping and restarting it does not help, it stays freezed.

**Comment by johnday-github** [comment]
Ah, sorry about that, not surprised I missed something while adding the pingpong - will look at this ASAP

**Comment by johnday-github** [comment]
I know you haven't got it in ping pong mode, but I had to rewrite quite a lot under the bonnet so this is definitely something just introduced due to the rewrite.

**Comment by johnday-github** [comment]
btw, is the pauses in the clip above just the recording and not actual realtime?

**Comment by johnday-github** [comment]
Have you got any other clues? I haven't been able to reproduced this yet, sure I'll find it but...

**Comment by magdesign** [comment]
A yes, its when EYE Layers 2 is activated on the mixer window, otherwise it works.

**Comment by magdesign** [comment]
the pauses are in the gif recording, its when looping...

**Comment by johnday-github** [comment]
yes, I've already included ping pong, rev and local speed to swapping/cloning in next release.

The EYE Layers 2 thing doesn't make sense, also not replicating it here. I'll keep looking.

**Comment by magdesign** [comment]
just digging to, can only replicate when chossing from a patch.... so maybe its because the patch with the EYE Layers 2 is saved on an older version...

**Comment by magdesign** [comment]
yes, confirm, its only when you store a patch with EYE Layers 2 included and then load the patch.

**Comment by johnday-github** [comment]
Ah, its more likely it an old take, I warned that some old takes (ie one without any parts) could cause problems. Its also possible that is the actual patch saving/loading is not quite working with the new code. This sounds like a good route to check. Thanks.

**Comment by magdesign** [comment]
you are right, with newer imported videos I can not cause the error.... so we might ignore and close the issue, will re-import my video library, no worries.

**Comment by johnday-github** [comment]
I've had a quick look over and still couldn't find anything, so I've released minor update 0.17.1 with the extra slot parameters being kept during cloning | swapping

**Comment by johnday-github** [comment]
FYI: you should only need to delete / edit the offending TAKE and re-save the patch
