### ISSUE TITLE
 Mapping the source faders to MIDI

### ISSUE THREAD

**Issue by jimruxton** [magdesign/IQSynth#18]
I am wondering if there is a way to map midi faders to the 4 faders beside sources in bus A and B. I find I use them quite a bit as I learn and it would be handy to use midi to control them. I couldn't find these faders in the midi mapping tool but I may just not know what they are called . Here is an image showing the faders I am referring to. Thanks!
![sourceFaders](https://user-images.githubusercontent.com/29495434/83599399-0c397600-a53a-11ea-9a8d-5804c1684c1b.png)

**Comment by johnday-github** [comment]
Your not missing anything, I've not added those to the midi mapping options yet, I'll do that shortly.

**Comment by jimruxton** [comment]
Great, thanks @johnday-github . The other midi control I'm longing for are the 8 effects slot faders. I hate asking for stuff though because the software is awesome already :) .

**Comment by jimruxton** [comment]
Thanks @magdesign . I have mapped those 4 parameters ok. It is the vertical sliders that bring in the actual effect that I was wondering about. I can trigger the sliders with pushbuttons but it would be nice to be able to fade them in manually via midi.

**Comment by johnday-github** [comment]
Hi @jimruxton, I've released a new version 0.18.2 which has Bus layer mix controls add to midi, find them under Bus(A|B), Bus, L1 to L4, I've also added FX level controls midi options to all relevant items, F1-F8 -> 'Mix Level'.

**Comment by jimruxton** [comment]
Wow this is great. Looking forward to try it out later tonight.

**Comment by jimruxton** [comment]
@johnday-github just confirming that this works great . Thanks so much for adding these features. Feel free to close this issue.

**Comment by johnday-github** [comment]
:)
