### ISSUE TITLE
Store a full FX Slot as a Patch

### ISSUE THREAD

**Issue by magdesign** [magdesign/IQSynth#2]
FX like Zoom, Scale and Tint are used on every media, so it would be nice to simply add a predefined Patch where all the "standard" FX are stored (without any media).
The user could then easy assign the FX stack Patch to the media.

**Comment by johnday-github** [comment]
That's what the AuxFX rack is for, you can make 'aux patches'  of your favorite setups and either apply them to the current outputs|bus or drag and drop them onto a slot for an instance fx stack setup.

**Comment by magdesign** [comment]
Got it, here is a screenshot on how to do this:
![store_fx](https://user-images.githubusercontent.com/5273166/79961602-4158a000-8487-11ea-80d8-fb25880dfe15.png)

**Comment by johnday-github** [comment]
can this be closed?
