### ISSUE TITLE
Driving multiple FX plugins with audio and macros

### ISSUE THREAD

**Issue by jimruxton** [magdesign/IQSynth#20]
I am wondering if there is a way to have multiple plugins running audio controlled macros. Currently if I set up macros to drive an FX plugin the macros are only active if that FX has focus. Once I set up the macros for that plugin and I select another plugin the first macro stops. I am wondering if this is expected behaviour? It would be nice to have multiple macros running.

**Comment by johnday-github** [comment]
Hi @jimruxton, the macros will semi-auto populate with what ever plugin has focus, unless you have dragged-drop a parameter on to a macro. In which case it should lock the macro to that parameter. At the moment you have 4 parameters per stack.
Note: you can just about drag-drop your locked macros from the main display to the trashcan to eject them (need to make this a little less fiddly, and more obvious), or use the 'x' button on it panel in the config window.

It use to be 8 parameters per stack, but that got/was messy and seemed overkill, I known anything is possible but I want a program that doesn't require a PHD to use. I'm not trying to produce a node based system, connecting everything to everything. I'm still working on improving the setup in a couple of ways, but until I do some R&D I'm haven't fallen one way or another yet.  I'll be adding beat options, multi parameters per macro, might integrate the macro config as a toggle panel between tapes and macro setup, I don't like the pop-up config window, but not sure how to improve it yet.

**Comment by jimruxton** [comment]
Thanks for the explanation @johnday-github . I didn't realize you could drag and drop parameters. Now that I know that, it's behaving exactly as I would want it to and I think 4 per stack is plenty for me to wrap my head around.
