### ISSUE TITLE
NDI Support

### ISSUE THREAD

**Issue by magdesign** [magdesign/IQSynth#22]
NDI is a protocol to send video over network nearly latency free.

You can get the SDK here:
https://www.ndi.tv/sdk/#download

We could for example send the output of IQsynth to another computer which is running a video mapping software via NDI or feed several screens which have an NDI receiver/monitor.

Or we could receive NDI streams in IQSynth instead of an USB camera.

There is a demo viewer/monitor for NDI streams available: 
https://orfast.com/

I just place it here as a reminder when you are looking for a new challenge.... 
I currently use an USB video grabber to feed IQSynth output to MAPIO to be able to distort the output to a surface. This works pretty well so far.

**Comment by johnday-github** [comment]
After looking through the license agreement, I'm not going to bother with this for the time being

**Comment by magdesign** [comment]
Ok.
