### ISSUE TITLE
Videos constantly looping

### ISSUE THREAD

**Issue by magdesign** [magdesign/IQSynth#25]
After long break I tried out VIDIFOLD-0.26.4b

This time my videos in the slot do not loop anymore...  what am I missing?

Thanks for your hints!

**Comment by johnday-github** [comment]
Hi again,

make sure the 'LP' button is enabled, there is the global one and a local one

the global one in the top right row 'LP' buttons are (Loop, Bounce, Reverse) modes
![image](https://user-images.githubusercontent.com/2182139/121577882-f189bf00-ca21-11eb-9638-a3d6e1dc2ead.png)

These options take precedent for any triggered slot, unless they have been manually set and locked in the slot

Does that help?

**Comment by magdesign** [comment]
Thanks for your help!
Finally it works, i was nearly there but never clicked LP while the video was playing (which is essential, otherwise it losses its state).

Just thinking if it would be possible to label it with an 90° placed `8`

Your software is growing and getting better and better :-)

**Comment by johnday-github** [comment]
cool, thanks, I've replaced the 'LP' with an infinity sign for next release

**Comment by magdesign** [comment]
Thank you !!!
