### ISSUE TITLE
Global BPM to trigger values on FX stack

### ISSUE THREAD

**Issue by magdesign** [magdesign/IQSynth#4]
Use the Global BPM to trigger values of FX and/or Layer Opacity.

Similar to this:
![global_bpm](https://user-images.githubusercontent.com/5273166/79876988-fb023300-83eb-11ea-905e-c6f413cff82f.png)

See this video:
https://cloud.magdesign.ch/index.php/s/EL5zpK9r6myRgsx

**Comment by johnday-github** [comment]
Yep, the macro parameter were initial could drivers to indicate they could have behavior like this

**Comment by johnday-github** [comment]
Currently refactoring macros to make room for a start on something like these

**Comment by jimruxton** [comment]
I realize this is a bit of a hack on a way to do this using MIDI but I put a small section in the WIKI on a possible way to implement this now using an external program like PD [https://github.com/magdesign/IQSynth/wiki/Remote-Control](url)

**Comment by johnday-github** [comment]
@jimruxton took a while for me to work out where your write up was for some reason, but found it today, very helpful thank you.

@magdesign, I've just moved the Macro options into the main GUI, the panel display is now toggled using F12 or a button on far right/bottom of the Aux panel. Its a little undesigned still but I'm happy its not floating in the way anymore and I'll start thinking about the BPM options for this now.

**Comment by johnday-github** [comment]
I've added some BPM linked options to the panel and rearranged the layout. (v0.19.1)
![macro-controls-v5](https://user-images.githubusercontent.com/2182139/87852391-7c893480-c8f9-11ea-90f9-30db846f7413.jpg)
will close this soon

**Comment by johnday-github** [comment]
It not obvious, but this allows a Ramp (pink button to turn use) min to max fitted to within the selected beat (8th > 8 bar) with mirror and swing and delay options. You can produce a Saw Tooth > Triangle Wave > Sine Wave > Pulse effects with this.

**Comment by magdesign** [comment]
![bpm_automation](https://user-images.githubusercontent.com/5273166/87907852-abbcb480-ca65-11ea-8ed5-39c34bfd16b1.gif)

This is amazing.
Thank you so much for adding this!

What I did not get while playing with it: how could I set a range

**Comment by jimruxton** [comment]
Thanks very much for this feature. Very useful.

**Comment by johnday-github** [comment]
:)
