### ISSUE TITLE
Quick Play Range adjustment

### ISSUE THREAD

**Issue by magdesign** [magdesign/IQSynth#5]
A quick way to adjust the IN/OUT point of a media, 
see the orange sliders below the media which could be moved by mouse:

![set_play_range](https://user-images.githubusercontent.com/5273166/79877768-f1c59600-83ec-11ea-8d0e-85d97266adcb.png)

**Comment by johnday-github** [comment]
will think about it, but will tackle the video editor bugs / improvements first

**Comment by johnday-github** [comment]
I'm thinking these controls would be just for quick and dirty live looping and take generation, so:

1. add rough in/out controls (might look different to your example)
2. these would make the source playback loop/re-trigger within this area
2.1 needs to take into account the retrigger modes
2.2 needs to take into account the current take being used
3. add a 'Quick Take' option to the take selection button under the input preview
3.1 this would pop up a naming option, auto filled to human readable datetime
3.2 this would save the take (with the 1 part) for future use and editing as usual

**Comment by johnday-github** [comment]
working on this

**Comment by johnday-github** [comment]
this was a little more work then expected, but see v0.16.18, after selecting range store and switch to new take by using the '+' next to the take drop option (no naming option included at this level, change name in video editor)

**Comment by magdesign** [comment]
this is great, perfect!

![range](https://user-images.githubusercontent.com/5273166/81535230-b83bd700-9369-11ea-92af-e6340984cb62.gif)

**Comment by magdesign** [comment]
This feature is currently broken.
Tested in v0.24.13 and newest download v0.24.14

Issue:
when moving one of the arrow slider, it will always loop the first few frames of the video, no matter where they are placed.

**Comment by johnday-github** [comment]
Hi Marc,

I have partially reproduce this, although what I'm seeing is the feedback on the control is wrong rather than the frames used.

I'll look into this next.

**Comment by johnday-github** [comment]
Hi Marc,

I have partially reproduce this, although what I'm seeing is the feedback on the control is wrong rather than the frames used.

I'll look into this next.

**Comment by johnday-github** [comment]
Was having trouble fully reproducing this but have now, seems to be on freshly loaded slots.

**Comment by magdesign** [comment]
forgot to mention, its on fresh installed ubuntu 20.04 lts system with newly imported media.

**Comment by johnday-github** [comment]
Try v0.24.15,  I think I tracked it down, it looks like it was broken for some time

**Comment by magdesign** [comment]
Just tested the new v0.24.15 build and it works also here again.
Thank you so much for your super quick bugfixing!!!!
