### ISSUE TITLE
Playback 

### ISSUE THREAD

**Issue by magdesign** [magdesign/IQSynth#6]
When selecting reverse play only, nothing happens:
![reverse_play](https://user-images.githubusercontent.com/5273166/79878387-a790e480-83ed-11ea-85cd-114086af504a.png)
Idea: play media in reverse.

**Comment by magdesign** [comment]
When selecting forward and reverse playback, video shall be played in ping-pong mode (according to the range set):

![ping-pong](https://user-images.githubusercontent.com/5273166/79878594-e45cdb80-83ed-11ea-8bbc-458156ae9813.png)

**Comment by johnday-github** [comment]
its a wanted improvement, lets put it on the pile

**Comment by johnday-github** [comment]
chasing ping-pong now

**Comment by johnday-github** [comment]
Added Ping-pong playback mode (requires a little bit of follow through, but is very usable), v0.17.0

**Comment by magdesign** [comment]
This is brilliant, together with the quick playrange adjustment a killer feature!

![pinpong](https://user-images.githubusercontent.com/5273166/82265549-82997e00-9967-11ea-8030-c1ddccae00dd.gif)

Thank you so much for adding this
