### ISSUE TITLE
FX Brightness/Contrast/Saturation missing

### ISSUE THREAD

**Issue by magdesign** [magdesign/IQSynth#7]
Would be very nice to have an FX for: Brightness/Contrast/Saturation

**Comment by johnday-github** [comment]
I currently use the ColorShift plugin, it has all those.

**Comment by magdesign** [comment]
Yes, that was I was looking for:

![colourshift](https://user-images.githubusercontent.com/5273166/80153510-f9886480-85bd-11ea-973d-bc0b0895add4.png)

**Comment by johnday-github** [comment]
can we close this issue then?
